services:
  psql-db:
    image: postgres:16
    container_name: psql-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    hostname: localhost
    volumes:
      - db-volume:/var/lib/postgresql/data
      - ./postgresql_config/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgresql_config/pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 20s
      retries: 5

  react-app:
    build: ./react-app
    container_name: react-app
    hostname: react-app
    ports:
      - "5173:5173"
    depends_on:
      - psql-db
      - flask-backend
    volumes:
      - ./react-app:/app
      - /app/node_modules
    environment:
      DB_HOST: psql-db

  flask-backend:
    build: ./FlaskWebProject
    container_name: flask-backend
    ports:
      - "5434:5434"
    depends_on:
      psql-db:
        condition: service_healthy
    environment:
      RDS_USERNAME: ${POSTGRES_USER}
      RDS_PASSWORD: ${POSTGRES_PASSWORD}
      RDS_HOSTNAME: psql-db
      RDS_PORT: 5432
      RDS_DB_NAME: ${POSTGRES_DB}
    volumes:
      - ./FlaskWebProject/FlaskWebProject:/app/app

volumes:
  db-volume:
networks:
  ${NETWORK_NAME}:
    driver: bridge
